// <auto-generated />
using System;
using Bokado.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Bokado.Server.Migrations
{
    [DbContext(typeof(SocialNetworkContext))]
    [Migration("20260528120000_AddNotifications")]
    partial class AddNotifications
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Bokado.Server.Models.Challenge", b =>
                {
                    b.Property<int>("ChallengeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("ChallengeId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("Reward")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ChallengeId");

                    b.ToTable("challenges");

                    b.HasData(
                        new
                        {
                            ChallengeId = 1,
                            CreatedAt = new DateTime(2025, 5, 21, 20, 30, 0, 0, DateTimeKind.Utc),
                            Description = "Почни спілкуватися з 3 різними людьми",
                            IsActive = false,
                            Reward = 2,
                            Title = "Соціальний старт"
                        },
                        new
                        {
                            ChallengeId = 2,
                            CreatedAt = new DateTime(2025, 5, 21, 20, 30, 0, 0, DateTimeKind.Utc),
                            Description = "Відправ 10 повідомлень у чатах",
                            IsActive = false,
                            Reward = 2,
                            Title = "Активний учасник"
                        },
                        new
                        {
                            ChallengeId = 3,
                            CreatedAt = new DateTime(2025, 5, 21, 20, 30, 0, 0, DateTimeKind.Utc),
                            Description = "Прийми участь у будь-якій події",
                            IsActive = false,
                            Reward = 1,
                            Title = "Знайомство з подією"
                        },
                        new
                        {
                            ChallengeId = 4,
                            CreatedAt = new DateTime(2025, 5, 21, 20, 30, 0, 0, DateTimeKind.Utc),
                            Description = "Додай 5 нових людей у друзі",
                            IsActive = false,
                            Reward = 2,
                            Title = "Дружелюбний крок"
                        },
                        new
                        {
                            ChallengeId = 5,
                            CreatedAt = new DateTime(2025, 5, 21, 20, 30, 0, 0, DateTimeKind.Utc),
                            Description = "Підтримуй бесіду в 3 різних чатах",
                            IsActive = false,
                            Reward = 1,
                            Title = "Чат-ентузіаст"
                        },
                        new
                        {
                            ChallengeId = 6,
                            CreatedAt = new DateTime(2025, 5, 21, 20, 30, 0, 0, DateTimeKind.Utc),
                            Description = "Створи власну подію",
                            IsActive = false,
                            Reward = 3,
                            Title = "Організатор"
                        },
                        new
                        {
                            ChallengeId = 7,
                            CreatedAt = new DateTime(2025, 5, 21, 20, 30, 0, 0, DateTimeKind.Utc),
                            Description = "Знайди 7 людей зі спільними інтересами",
                            IsActive = false,
                            Reward = 2,
                            Title = "Дослідник"
                        },
                        new
                        {
                            ChallengeId = 8,
                            CreatedAt = new DateTime(2025, 5, 21, 20, 30, 0, 0, DateTimeKind.Utc),
                            Description = "Відправ хоча б одне голосове повідомлення",
                            IsActive = false,
                            Reward = 1,
                            Title = "Віртуальний зустріч"
                        },
                        new
                        {
                            ChallengeId = 9,
                            CreatedAt = new DateTime(2025, 5, 21, 20, 30, 0, 0, DateTimeKind.Utc),
                            Description = "Відвідай 2 різні події за тиждень",
                            IsActive = false,
                            Reward = 3,
                            Title = "Соціальний активіст"
                        },
                        new
                        {
                            ChallengeId = 10,
                            CreatedAt = new DateTime(2025, 5, 21, 20, 30, 0, 0, DateTimeKind.Utc),
                            Description = "Заповни всі поля свого профілю на 100%",
                            IsActive = false,
                            Reward = 1,
                            Title = "Профільний експерт"
                        },
                        new
                        {
                            ChallengeId = 11,
                            CreatedAt = new DateTime(2025, 5, 21, 20, 30, 0, 0, DateTimeKind.Utc),
                            Description = "Опублікуй свій перший пост",
                            IsActive = false,
                            Reward = 1,
                            Title = "Перший пост"
                        },
                        new
                        {
                            ChallengeId = 12,
                            CreatedAt = new DateTime(2025, 5, 21, 20, 30, 0, 0, DateTimeKind.Utc),
                            Description = "Отримай 5 лайків на один пост",
                            IsActive = false,
                            Reward = 2,
                            Title = "Популярний контент"
                        },
                        new
                        {
                            ChallengeId = 13,
                            CreatedAt = new DateTime(2025, 5, 21, 20, 30, 0, 0, DateTimeKind.Utc),
                            Description = "Вступи в свою першу групу",
                            IsActive = false,
                            Reward = 1,
                            Title = "Груповий учасник"
                        },
                        new
                        {
                            ChallengeId = 14,
                            CreatedAt = new DateTime(2025, 5, 21, 20, 30, 0, 0, DateTimeKind.Utc),
                            Description = "Створи власну групу",
                            IsActive = false,
                            Reward = 3,
                            Title = "Лідер спільноти"
                        },
                        new
                        {
                            ChallengeId = 15,
                            CreatedAt = new DateTime(2025, 5, 21, 20, 30, 0, 0, DateTimeKind.Utc),
                            Description = "Надішли фото у повідомленні",
                            IsActive = false,
                            Reward = 1,
                            Title = "Фотограф"
                        },
                        new
                        {
                            ChallengeId = 16,
                            CreatedAt = new DateTime(2025, 5, 21, 20, 30, 0, 0, DateTimeKind.Utc),
                            Description = "Запусти відеодзвінок у групі",
                            IsActive = false,
                            Reward = 2,
                            Title = "Відеоорганізатор"
                        },
                        new
                        {
                            ChallengeId = 17,
                            CreatedAt = new DateTime(2025, 5, 21, 20, 30, 0, 0, DateTimeKind.Utc),
                            Description = "Отримай 3 запити на дружбу",
                            IsActive = false,
                            Reward = 2,
                            Title = "Магніт"
                        },
                        new
                        {
                            ChallengeId = 18,
                            CreatedAt = new DateTime(2025, 5, 21, 20, 30, 0, 0, DateTimeKind.Utc),
                            Description = "Набери 10 друзів",
                            IsActive = false,
                            Reward = 3,
                            Title = "Відданий друг"
                        },
                        new
                        {
                            ChallengeId = 19,
                            CreatedAt = new DateTime(2025, 5, 21, 20, 30, 0, 0, DateTimeKind.Utc),
                            Description = "Постав 10 лайків на пости інших",
                            IsActive = false,
                            Reward = 1,
                            Title = "Активний лайкер"
                        },
                        new
                        {
                            ChallengeId = 20,
                            CreatedAt = new DateTime(2025, 5, 21, 20, 30, 0, 0, DateTimeKind.Utc),
                            Description = "Вступи в 3 різні групи",
                            IsActive = false,
                            Reward = 3,
                            Title = "Командний гравець"
                        });
                });

            modelBuilder.Entity("Bokado.Server.Models.Chat", b =>
                {
                    b.Property<int>("ChatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("ChatId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ChatId");

                    b.ToTable("chats");
                });

            modelBuilder.Entity("Bokado.Server.Models.ChatParticipant", b =>
                {
                    b.Property<int>("ChatParticipantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("ChatParticipantId"));

                    b.Property<int>("ChatId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("ChatParticipantId");

                    b.HasIndex("ChatId");

                    b.HasIndex("UserId");

                    b.ToTable("chat_participants");
                });

            modelBuilder.Entity("Bokado.Server.Models.Event", b =>
                {
                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("EventId"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatorId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Maximum")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("EventId");

                    b.HasIndex("CreatorId");

                    b.ToTable("events");
                });

            modelBuilder.Entity("Bokado.Server.Models.EventParticipant", b =>
                {
                    b.Property<int>("EventParticipantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("EventParticipantId"));

                    b.Property<int>("EventId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("EventParticipantId");

                    b.HasIndex("EventId");

                    b.HasIndex("UserId");

                    b.ToTable("event_participants");
                });

            modelBuilder.Entity("Bokado.Server.Models.FriendRequest", b =>
                {
                    b.Property<int>("FriendRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("FriendRequestId"));

                    b.Property<int>("FromUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ToUserId")
                        .HasColumnType("integer");

                    b.HasKey("FriendRequestId");

                    b.HasIndex("ToUserId");

                    b.HasIndex("FromUserId", "ToUserId")
                        .IsUnique();

                    b.ToTable("friend_requests");
                });

            modelBuilder.Entity("Bokado.Server.Models.Friendship", b =>
                {
                    b.Property<int>("FriendshipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("FriendshipId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FriendId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("FriendshipId");

                    b.HasIndex("FriendId");

                    b.HasIndex("UserId");

                    b.ToTable("friendships");
                });

            modelBuilder.Entity("Bokado.Server.Models.Group", b =>
                {
                    b.Property<int>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("GroupId"));

                    b.Property<int>("ChatId")
                        .HasColumnType("integer");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatorId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("GroupId");

                    b.HasIndex("ChatId");

                    b.HasIndex("CreatorId");

                    b.ToTable("groups");
                });

            modelBuilder.Entity("Bokado.Server.Models.GroupInterest", b =>
                {
                    b.Property<int>("GroupInterestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("GroupInterestId"));

                    b.Property<int>("GroupId")
                        .HasColumnType("integer");

                    b.Property<int>("InterestId")
                        .HasColumnType("integer");

                    b.HasKey("GroupInterestId");

                    b.HasIndex("GroupId");

                    b.HasIndex("InterestId");

                    b.ToTable("group_interests");
                });

            modelBuilder.Entity("Bokado.Server.Models.GroupMember", b =>
                {
                    b.Property<int>("GroupMemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("GroupMemberId"));

                    b.Property<int>("GroupId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("GroupMemberId");

                    b.HasIndex("GroupId");

                    b.HasIndex("UserId");

                    b.ToTable("group_members");
                });

            modelBuilder.Entity("Bokado.Server.Models.Interest", b =>
                {
                    b.Property<int>("InterestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("InterestId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("InterestId");

                    b.ToTable("interests");

                    b.HasData(
                        new
                        {
                            InterestId = 1,
                            Name = "Ігри"
                        },
                        new
                        {
                            InterestId = 2,
                            Name = "Музика"
                        },
                        new
                        {
                            InterestId = 3,
                            Name = "Кіно"
                        },
                        new
                        {
                            InterestId = 4,
                            Name = "Спорт"
                        },
                        new
                        {
                            InterestId = 5,
                            Name = "Подорожі"
                        },
                        new
                        {
                            InterestId = 6,
                            Name = "Кулінарія"
                        },
                        new
                        {
                            InterestId = 7,
                            Name = "Мистецтво"
                        },
                        new
                        {
                            InterestId = 8,
                            Name = "Технології"
                        },
                        new
                        {
                            InterestId = 9,
                            Name = "Книги"
                        },
                        new
                        {
                            InterestId = 10,
                            Name = "Фітнес"
                        },
                        new
                        {
                            InterestId = 11,
                            Name = "Фотографія"
                        },
                        new
                        {
                            InterestId = 12,
                            Name = "Природа"
                        });
                });


            modelBuilder.Entity("Bokado.Server.Models.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("NotificationId"));

                    b.Property<int?>("ActorId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Link")
                        .HasColumnType("text");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("NotificationId");

                    b.HasIndex("ActorId");

                    b.HasIndex("UserId");

                    b.ToTable("notifications");
                });

            modelBuilder.Entity("Bokado.Server.Models.Message", b =>
                {
                    b.Property<int>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("MessageId"));

                    b.Property<string>("Attachment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ChatId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<int>("SenderId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MessageId");

                    b.HasIndex("ChatId");

                    b.HasIndex("SenderId");

                    b.ToTable("messages");
                });

            modelBuilder.Entity("Bokado.Server.Models.Post", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("PostId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Text")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("PostId");

                    b.HasIndex("UserId");

                    b.ToTable("posts");
                });

            modelBuilder.Entity("Bokado.Server.Models.PostLike", b =>
                {
                    b.Property<int>("PostLikeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("PostLikeId"));

                    b.Property<DateTime>("LikedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PostId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("PostLikeId");

                    b.HasIndex("UserId");

                    b.HasIndex("PostId", "UserId")
                        .IsUnique();

                    b.ToTable("post_likes");
                });

            modelBuilder.Entity("Bokado.Server.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("UserId"));

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<string>("Bio")
                        .HasColumnType("text");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("timestamp with time zone");

                  b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsBanned")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPremium")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastActive")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("UserId");

                    b.ToTable("users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            BirthDate = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@example.com",
                            IsAdmin = true,
                            IsBanned = false,
                            IsPremium = false,
                            LastActive = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Level = 1,
                            PasswordHash = "$2a$11$QVlAssqGxFq2bvc4kKYI4O/K/bD5UQpcClAbDS/f9W81551lIEgri",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("Bokado.Server.Models.UserChallenge", b =>
                {
                    b.Property<int>("UserChallengeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("UserChallengeId"));

                    b.Property<int>("ChallengeId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("UserChallengeId");

                    b.HasIndex("ChallengeId");

                    b.HasIndex("UserId");

                    b.ToTable("user_challenges");
                });

            modelBuilder.Entity("Bokado.Server.Models.UserInterest", b =>
                {
                    b.Property<int>("UserInterestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("UserInterestId"));

                    b.Property<int>("InterestId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("UserInterestId");

                    b.HasIndex("InterestId");

                    b.HasIndex("UserId");

                    b.ToTable("user_interests");
                });

            modelBuilder.Entity("Bokado.Server.Models.ChatParticipant", b =>
                {
                    b.HasOne("Bokado.Server.Models.Chat", "Chat")
                        .WithMany("Participants")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bokado.Server.Models.User", "User")
                        .WithMany("ChatParticipants")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chat");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Bokado.Server.Models.Event", b =>
                {
                    b.HasOne("Bokado.Server.Models.User", "Creator")
                        .WithMany("CreatedEvents")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("Bokado.Server.Models.EventParticipant", b =>
                {
                    b.HasOne("Bokado.Server.Models.Event", "Event")
                        .WithMany("Participants")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bokado.Server.Models.User", "User")
                        .WithMany("EventParticipants")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Bokado.Server.Models.FriendRequest", b =>
                {
                    b.HasOne("Bokado.Server.Models.User", "FromUser")
                        .WithMany("SentFriendRequests")
                        .HasForeignKey("FromUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Bokado.Server.Models.User", "ToUser")
                        .WithMany("ReceivedFriendRequests")
                        .HasForeignKey("ToUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromUser");

                    b.Navigation("ToUser");
                });

            modelBuilder.Entity("Bokado.Server.Models.Friendship", b =>
                {
                    b.HasOne("Bokado.Server.Models.User", "Friend")
                        .WithMany()
                        .HasForeignKey("FriendId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Bokado.Server.Models.User", "User")
                        .WithMany("Friends")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Friend");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Bokado.Server.Models.Group", b =>
                {
                    b.HasOne("Bokado.Server.Models.Chat", "Chat")
                        .WithMany()
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bokado.Server.Models.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Chat");

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("Bokado.Server.Models.GroupInterest", b =>
                {
                    b.HasOne("Bokado.Server.Models.Group", "Group")
                        .WithMany("GroupInterests")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bokado.Server.Models.Interest", "Interest")
                        .WithMany()
                        .HasForeignKey("InterestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Interest");
                });

            modelBuilder.Entity("Bokado.Server.Models.GroupMember", b =>
                {
                    b.HasOne("Bokado.Server.Models.Group", "Group")
                        .WithMany("Members")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bokado.Server.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Bokado.Server.Models.Message", b =>
                {
                    b.HasOne("Bokado.Server.Models.Chat", "Chat")
                        .WithMany("Messages")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bokado.Server.Models.User", "Sender")
                        .WithMany("Messages")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chat");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("Bokado.Server.Models.Post", b =>
                {
                    b.HasOne("Bokado.Server.Models.User", "Author")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("Bokado.Server.Models.PostLike", b =>
                {
                    b.HasOne("Bokado.Server.Models.Post", "Post")
                        .WithMany("Likes")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bokado.Server.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Bokado.Server.Models.Notification", b =>
                {
                    b.HasOne("Bokado.Server.Models.User", "Actor")
                        .WithMany()
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Bokado.Server.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actor");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Bokado.Server.Models.UserChallenge", b =>
                {
                    b.HasOne("Bokado.Server.Models.Challenge", "Challenge")
                        .WithMany("UserChallenges")
                        .HasForeignKey("ChallengeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bokado.Server.Models.User", "User")
                        .WithMany("UserChallenges")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Challenge");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Bokado.Server.Models.UserInterest", b =>
                {
                    b.HasOne("Bokado.Server.Models.Interest", "Interest")
                        .WithMany("UserInterests")
                        .HasForeignKey("InterestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bokado.Server.Models.User", "User")
                        .WithMany("UserInterests")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Interest");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Bokado.Server.Models.Challenge", b =>
                {
                    b.Navigation("UserChallenges");
                });

            modelBuilder.Entity("Bokado.Server.Models.Chat", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("Participants");
                });

            modelBuilder.Entity("Bokado.Server.Models.Event", b =>
                {
                    b.Navigation("Participants");
                });

            modelBuilder.Entity("Bokado.Server.Models.Group", b =>
                {
                    b.Navigation("GroupInterests");

                    b.Navigation("Members");
                });

            modelBuilder.Entity("Bokado.Server.Models.Interest", b =>
                {
                    b.Navigation("UserInterests");
                });

            modelBuilder.Entity("Bokado.Server.Models.Post", b =>
                {
                    b.Navigation("Likes");
                });

            modelBuilder.Entity("Bokado.Server.Models.User", b =>
                {
                    b.Navigation("ChatParticipants");

                    b.Navigation("CreatedEvents");

                    b.Navigation("EventParticipants");

                    b.Navigation("Friends");

                    b.Navigation("Messages");

                    b.Navigation("ReceivedFriendRequests");

                    b.Navigation("SentFriendRequests");

                    b.Navigation("UserChallenges");

                    b.Navigation("UserInterests");
                });
#pragma warning restore 612, 618
        }
    }
}
